name:                remotex
version:             0.1.0.0
github:              "githubuser/remotex"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2019 Author name here"

extra-source-files:
- README.md

description:         Please see the README on GitHub at <https://github.com/githubuser/remotex#readme>

dependencies:
- base >= 4.7 && < 5
- X11
- xtest
- wai
- warp
- wai-app-static
- wai-websockets
- text
- text-icu
- websockets
- directory
- process

executables:
  remotex-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
